-- Schema DDL
CREATE TABLE jobs(
	j_id NUMBER (7) GENERATED BY DEFAULT AS IDENTITY MINVALUE 100 MAXVALUE 1000 INCREMENT BY 1 START WITH 100 CACHE 20 ORDER NOT NULL,
	j_title VARCHAr2 (10),
	CONSTRAINT jobs_j_id_pk PRIMARY KEY (j_id)
);

-- Acepta entradas como:
-- select 'drop table '||table_name||' cascade constraints;' from user_tables;



CREATE TABLE employees(
	e_id NUMBER (7) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1000 MAXVALUE 1500 INCREMENT BY 1 START WITH 1000 CACHE 20 ORDER NOT NULL,
	e_name VARCHAR2 (30),
	e_phone NUMBER (11),
	e_address VARCHAR2 (50),
	e_salary NUMBER (6),
    e_status VARCHAR2 (30),
	j_id NUMBER (5),
	CONSTRAINT employees_e_id_pk PRIMARY KEY (e_id),
	CONSTRAINT employees_j_id_fk FOREIGN KEY (j_id) REFERENCES jobs (j_id) ON DELETE CASCADE
);

CREATE TABLE tables(
	t_id NUMBER (5) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOT NULL,
	capacity NUMBER (2),
	e_id NUMBER (7),
	CONSTRAINT tables_t_id_pk PRIMARY KEY (t_id),
	CONSTRAINT tables_e_id_fk FOREIGN KEY (e_id) REFERENCES employees (e_id) ON DELETE CASCADE
);


CREATE TABLE foods(
	f_id NUMBER (7) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 10 CACHE 20 ORDER NOT NULL,
	f_type VARCHAR2 (30),
	f_name VARCHAR2 (40),
	f_description VARCHAR2 (100),
	f_price NUMBER (5),
	CONSTRAINT foods_f_id_pk PRIMARY KEY (f_id)
);

CREATE TABLE customers(
	c_id NUMBER (7) GENERATED BY DEFAULT AS IDENTITY MINVALUE 2000 MAXVALUE 2500 INCREMENT BY 1 START WITH 2000 CACHE 20 ORDER NOT NULL,
	c_name VARCHAR2 (30),
	c_phone NUMBER (11),
	c_address VARCHAR2 (50),
	c_status VARCHAR2 (50),
	CONSTRAINT customers_c_id_pk PRIMARY KEY (c_id)
);

CREATE TABLE orders(
	o_id NUMBER (7) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOT NULL,
	o_status VARCHAR2 (30),
    o_type VARCHAR2 (30),
    o_total VARCHAR2 (30),
	o_date DATE DEFAULT SYSDATE,
	c_id NUMBER (7),
	CONSTRAINT orders_o_id_pk PRIMARY KEY (o_id),
	CONSTRAINT orders_cid_fk FOREIGN KEY (c_id) REFERENCES customers (c_id) ON DELETE CASCADE
);


-- CREATE TABLE order_history(
-- 	t_id NUMBER (5),
-- 	o_id NUMBER (7),
-- 	CONSTRAINT order_history_PK PRIMARY KEY (t_id, O_id),
-- 	CONSTRAINT order_history_tid_fk FOREIGN KEY (t_id) REFERENCES tables (t_id) ON DELETE CASCADE,
-- 	CONSTRAINT order_history_oid_fk FOREIGN KEY (o_id) REFERENCES orders (o_id) ON DELETE CASCADE
-- );

CREATE TABLE items(
	quantity NUMBER (4),
	o_id NUMBER (7),
	f_id NUMBER (7),
	CONSTRAINT items_oid_fid_pk PRIMARY KEY (o_id, f_id),
	CONSTRAINT items_oid_fk FOREIGN KEY (o_id) REFERENCES orders (o_id) ON DELETE CASCADE,
	CONSTRAINT items_fid_fk FOREIGN KEY (f_id) REFERENCES foods (f_id) ON DELETE CASCADE
);

CREATE TABLE booking(
	b_date DATE,
	b_hour NUMBER(2),
	c_id NUMBER (7),
	t_id NUMBER (5),
	CONSTRAINT booking_cid_tid_pk PRIMARY KEY (c_id, t_id),
	CONSTRAINT booing_cid_fk FOREIGN KEY (c_id) REFERENCES customers(c_id) ON DELETE CASCADE,
	CONSTRAINT booing_tid_fk FOREIGN KEY (t_id) REFERENCES tables (t_id) ON DELETE CASCADE
);

